name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install
      - run: pnpm run build

      - name: Save files action
        uses: LarchLiu/actions-save-files@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: publish
          publish_dir: ./app/bot/telegram-cl/dist, ./app/extension/chrome/dist
          full_commit_message: ${{ github.event.head_commit.message }}

      - name: Zip extension
        uses: vimtor/action-zip@v1.1
        with:
          files: ./app/extension/chrome/dist
          recursive: false
          dest: ./chrome-extension.zip

      - run: npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release id
        id: get-release-id
        run: echo "release_id=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq '.id' | sed 's/\"//g')" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        id: upload-release-asset
        uses: LarchLiu/upload-release-assets@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: ${{ github.repository }}
          release_id: ${{ steps.get-release-id.outputs.release_id }}
          asset_path: ./chrome-extension.zip
          asset_name: chrome-extension.zip
          asset_content_type: application/zip
